# Site settings
title: Veracode2Rally
description: "A DevOps tool for integrating Veracode with Rally"
baseurl: /veracode2rally
url: "https://securedevops.github.io" 
tagline: A DevOps tool for integrating Veracode scan results with Rally 

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title

gems: [jekyll-paginate, jekyll-gist]
